api = "0.4"

[buildpack]
id = "fagiani/apt"
version = "0.2.4"
name = "apt Packages Buildpack"
homepage = "https://github.com/fagiani/apt-buildpack"
description = "Installs apt packages for further builds and runtime"
keywords = ["apt", "packages", "ubuntu"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.buildpacks.stacks.jammy"
